name: Apply GitHub labels

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies from npm
        run: npm ci

      - name: Sync GitHub labels
        run: ./apply.sh
        env:
          APPLY: true
          GITHUB_ACCESS_TOKEN: ${{ secrets.DESIGN_SYSTEM_GITHUB_TOKEN }}

