name: Test GitHub labels

on: pull_request

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies from npm
        run: npm ci

      - name: Test
        run: node validate.js

      - name: Dry run
        run: ./apply.sh | tee $GITHUB_WORKSPACE/apply.log
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.DESIGN_SYSTEM_GITHUB_TOKEN }}

        # Post comment with dry run output, if PR isn't from a fork
      - if: github.event.pull_request.head.repo.full_name == github.repository
        name: Add comment to PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises
            const log = await fs.readFile(
              process.env.GITHUB_WORKSPACE + '/apply.log', 'utf8'
            )
            const commentText = '## Output from dry-run\n' +
              '```\n' +
              log +
              '\n```'
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentText
            })
